# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:
#  - pwsh: |
#      Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_enterprise.exe -OutFile vs_enterprise.exe
#  - script: |
#      vs_enterprise.exe --version --quiet
#  - script: |
#      vs_enterprise.exe modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --add Microsoft.VisualStudio.Component.VC.v141.x86.x64 --quiet --norestart --includeRecommended

 - pwsh: choco install visualstudio2019enterprise --package-parameters '--add Microsoft.VisualStudio.Component.VC.v141.x86.x64 --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"'

 - script: |
     dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC"
