pool:
  vmImage: 'windows-2022'

trigger:
  - main
  - release/*

stages:
- stage: Build
  jobs:
  - job: Build

    steps:
    - checkout: self
      clean: 'true'
      fetchDepth: 0
      
    - pwsh: |
        $DotNetRoot = "C:\hostedtoolcache\windows\dotnet"
        Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./build/installcli.ps1"
        & ./build/installcli.ps1 -c 9.0 -q daily -InstallDir $DotNetRoot

      condition: and(succeeded(), eq( variables['Agent.OS'], 'Windows_NT' ))
      displayName: 'Setup .NET (Windows)'

    - pwsh: |
        wget https://dot.net/v1/dotnet-install.sh
        chmod +x dotnet-install.sh
        ./dotnet-install.sh -c 9.0 -q daily
        echo "[task.setvariable variable=PATH;]${env:PATH}:$env:HOME/.dotnet"
        echo "[task.setvariable variable=DOTNET_ROOT;]$env:HOME/.dotnet"

        echo "##vso[task.setvariable variable=PATH;]$env:HOME/.dotnet:${env:PATH}"
        echo "##vso[task.setvariable variable=DOTNET_ROOT;]$env:HOME/.dotnet"

      condition: and(succeeded(), ne( variables['Agent.OS'], 'Windows_NT' ))
      displayName: 'Setup .NET (Linux/macOS)'

    - pwsh: |
        cd src
        dotnet --version
        dotnet --list-sdks
        dotnet workload install wasm-tools
        dotnet workload install wasm-experimental

      displayName: Setup Workloads

    - pwsh: dotnet new wasmconsole -o testconsole01
    
    - pwsh: |
        cd testconsole01
        dotnet publish -p:WasmCachePath=$env:tmp\emsdk -p:WasmBuildNative=true /bl:$(Build.ArtifactStagingDirectory)\msbuild.binlog


    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: dotnet-sdk-binaries