pool:
  vmImage: 'windows-2019'

trigger:
  - master

steps:
  - pwsh: |
      dotnet tool update -g dotnet-vs
      vs install preview --quiet
  - pwsh: |
      vs where preview --prop=InstallationPath)\MSBuild\Current\Bin
  - pwsh: |
      vs where -all
