# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted MacOS
  
steps:
  - bash: ls -l /Applications
  - bash: cat $(Agent.HomeDirectory)/scripts/select-xamarin-sdk.sh 

# steps:
#  - pwsh: .\install-vs.ps1
#  - script: |
#      dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC"
