pool:
  vmImage: 'windows-2022'

trigger:
  - main
  - release/*

# steps:
#  - bash: |
#     whereis mono
#     sudo apt install gtk-sharp2
#     git clone --recurse-submodules https://github.com/mono/SkiaSharp.git
#     cd SkiaSharp
#     dotnet tool restore
#     dotnet cake --target=externals-download
#     msbuild /r /v:d /p:Configuration=Release /p:BuildingInsideUnoSourceGenerator=true source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SkiaSharp.Views.Uno.Wasm.csproj
#     # dotnet cake --target=libs --skipExternals="all"

# resources:
#   containers:
#   - container: nv-bionic-wasm
#     image: unoplatform/wasm-build:3.0

stages:
- stage: Build
  jobs:
  - job: Build

    # container:
    #   image: unoplatform/wasm-build:3.0
    #   options: "--name ci-container --shm-size=2gb"

    steps:
    - checkout: self
      clean: 'true'
      fetchDepth: 0

    - checkout: self
      clean: true
      
    - task: UseDotNet@2
      displayName: 'Use .NET SDK'
      retryCountOnTaskFailure: 3
      inputs:
        version: 8.0.201
        installationPath: '$(Build.SourcesDirectory)\dotnet'
        #includePreviewVersions: true

    - powershell: |
        echo Dotnet root: $env:DOTNET_ROOT

    - pwsh: |
        dotnet tool install --global Uno.Check --version 1.21.0-dev.3
        & uno-check -v --ci --non-interactive --fix --skip xcode --skip gtk3 --skip vswin --skip androidemulator --skip androidsdk --skip vsmac

    - pwsh: |
        dotnet workload update --print-rollback

    - powershell: |
        echo "##vso[task.setvariable variable=DotnetSdkPath]$env:DOTNET_ROOT"

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(DotnetSdkPath)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/dotnet.zip'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: dotnet-sdk-binaries

  - job: Build2
    dependsOn: Build

    steps:
    - checkout: self
      clean: 'true'
      fetchDepth: 0
      
    - task: UseDotNet@2
      displayName: 'Use .NET SDK'
      retryCountOnTaskFailure: 3
      inputs:
        version: 8.0.201
        installationPath: '$(Build.SourcesDirectory)\dotnet'
        #includePreviewVersions: true

    - powershell: |
        echo "##vso[task.setvariable variable=DotnetSdkPath]$env:DOTNET_ROOT"

    - task: DownloadPipelineArtifact@2
      displayName: Download .NET SDK
      inputs:
        artifact: dotnet-sdk-binaries
        path: $(Build.ArtifactStagingDirectory)

    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '(Build.ArtifactStagingDirectory)/dotnet.zip'
        destinationFolder: $(Build.SourcesDirectory)\dotnet


    - pwsh: |
        dotnet tool install --global Uno.Check --version 1.21.0-dev.3
        & uno-check -v --ci --non-interactive --fix --skip xcode --skip gtk3 --skip vswin --skip androidemulator --skip androidsdk --skip vsmac
