pool:
  vmImage: 'windows-2022'

trigger:
  - main
  - release/*

# steps:
#  - bash: |
#     whereis mono
#     sudo apt install gtk-sharp2
#     git clone --recurse-submodules https://github.com/mono/SkiaSharp.git
#     cd SkiaSharp
#     dotnet tool restore
#     dotnet cake --target=externals-download
#     msbuild /r /v:d /p:Configuration=Release /p:BuildingInsideUnoSourceGenerator=true source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SkiaSharp.Views.Uno.Wasm.csproj
#     # dotnet cake --target=libs --skipExternals="all"

# resources:
#   containers:
#   - container: nv-bionic-wasm
#     image: unoplatform/wasm-build:3.0

stages:
- stage: Build
  jobs:
  - job: Matrix_Gen
    displayName: Test Matrix Generation
    steps:
      - pwsh: |
          $matrixGroups = @{
              'MyList' = @{
                  'Group0' = @{
                      'validations' =
                          '
                            -preset recommended `
                            -preset blank `
                          '
                      'unoCheckArgs' = '--pre-major'
                  }
                  'Group1' = @{
                      'validations' = 
                          '
                            -preset recommended `
                            -preset blank `
                          '
                      'unoCheckArgs' = '--pre-major'
                  }
              }
          }

          $matrixAsJson = $matrixGroups | ConvertTo-Json

          echo "##vso[task.setVariable variable=legs;isOutput=true]$matrixAsJson.Replace('\\n','')"
        name: mtrx

  - job: runner
    dependsOn: Matrix_Gen
    strategy:
      matrix: $[ dependencies.Matrix_Gen.outputs['mtrx.legs'] ]
    steps:
    - script: echo $(myvar) # echos A or B depending on which leg is running
