pool:
  vmImage: 'ubuntu-18.04'

trigger:
  - master

steps:
 - bash:
    git clone --recurse-submodules https://github.com/mono/SkiaSharp.git
    cd SkiaSharp
    sudo pwsh ./scripts/install-dotnet.ps1 -Version 6.0.200-rtm.22107.3 -InstallDir '/usr/share/dotnet'
    $env:PATH = '/usr/share/dotnet:' + $env:PATH
    dotnet tool install -g cake.tool
    dotnet cake --target=externals-download
    dotnet cake --target=libs --skipExternals="all"