pool:
  vmImage: 'macOS-10.15'

trigger:
  - master

steps:
  - pwsh: Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.sh" -OutFile dotnet-install.sh
  - bash: sh dotnet-install.sh --version "6.0.200" --install-dir "/Users/runner/hostedtoolcache/dotnet" --verbose
  - pwsh: dotnet --info
