pool:
  vmImage: 'windows-2022'

trigger:
  - main
  - release/*

stages:
- stage: Build
  jobs:
  - job: Build

    steps:
    - checkout: self
      clean: 'true'
      fetchDepth: 0
      
    - pwsh: |
        $DotNetRoot = "C:\hostedtoolcache\windows\dotnet"
        Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile ".\installcli.ps1"
        & .\installcli.ps1 -c 9.0 -q daily -InstallDir $DotNetRoot

      condition: and(succeeded(), eq( variables['Agent.OS'], 'Windows_NT' ))
      displayName: 'Setup .NET (Windows)'

    - pwsh: |
        dotnet --version
        dotnet --list-sdks
        dotnet workload install wasm-tools
        dotnet workload install wasm-experimental

      displayName: Setup Workloads

    - pwsh: dotnet new wasmconsole -o testconsole01
    
    - pwsh: |
        cd testconsole01
        mkdir $env:TMP\emsdk
        dotnet publish -p:WasmCachePath=$env:TMP\emsdk -p:WasmBuildNative=true /bl:$(Build.ArtifactStagingDirectory)\msbuild.binlog


    - task: PublishPipelineArtifact@1
      condition: always()
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: dotnet-sdk-binaries