pool:
  vmImage: 'windows-2019'

trigger:
  - master

steps:
  - pwsh: .\scripts\install-vs.ps1 -Version '16/pre'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: output
      pathToPublish: 'output'
