pool:
  vmImage: 'ubuntu-latest'

trigger:
  - master

steps:
 - bash: |
    whereis mono
    sudo apt install gtk-sharp2
    git clone --recurse-submodules https://github.com/mono/SkiaSharp.git
    cd SkiaSharp
    dotnet tool restore
    dotnet cake --target=externals-download
    msbuild /r /v:d /p:Configuration=Release /p:UnoSourceGeneratorUseGenerationHost=true /p:UnoSourceGeneratorUseGenerationController=false source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SkiaSharp.Views.Uno.Wasm.csproj
    # dotnet cake --target=libs --skipExternals="all"
