pool:
  vmImage: 'windows-2022'

trigger:
  - main
  - release/*

# steps:
#  - bash: |
#     whereis mono
#     sudo apt install gtk-sharp2
#     git clone --recurse-submodules https://github.com/mono/SkiaSharp.git
#     cd SkiaSharp
#     dotnet tool restore
#     dotnet cake --target=externals-download
#     msbuild /r /v:d /p:Configuration=Release /p:BuildingInsideUnoSourceGenerator=true source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SkiaSharp.Views.Uno.Wasm.csproj
#     # dotnet cake --target=libs --skipExternals="all"

# resources:
#   containers:
#   - container: nv-bionic-wasm
#     image: unoplatform/wasm-build:3.0

stages:
- stage: Build
  jobs:
  - job: Build

    # container:
    #   image: unoplatform/wasm-build:3.0
    #   options: "--name ci-container --shm-size=2gb"

    steps:
    - checkout: self
      clean: 'true'
      fetchDepth: 0

    - checkout: self
      clean: true
      
    - task: UseDotNet@2
      displayName: 'Use .NET SDK'
      retryCountOnTaskFailure: 3
      inputs:
        version: 9.x
        includePreviewVersions: true

    - pwsh: |
        dotnet workload install ios macos android maccatalyst

    - pwsh: |
        dotnet workload update --print-rollback
 