pool:
  vmImage: 'macos-latest'

trigger:
- master

steps:
  - bash: ls -l /Applications
  - bash: ls -l /Library/Frameworks/Mono.framework/Versions
  - bash: ls -l /Library/Frameworks/Xamarin.iOS.framework/Versions
  - bash: ls -l /Library/Frameworks/Xamarin.Android.framework/Versions
  - bash: ls -l /Library/Frameworks/Xamarin.Mac.framework/Versions
