# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted MacOS
  
steps:
  - bash: ls -l /Applications
  - bash: ls -l /Library/Frameworks/Mono.framework/Versions
  - bash: ls -l /Library/Frameworks/Xamarin.iOS.framework/Versions
  - bash: ls -l /Library/Frameworks/Xamarin.Android.framework/Versions
  - bash: ls -l /Library/Frameworks/Xamarin.Mac.framework/Versions

# steps:
#  - pwsh: .\install-vs.ps1
#  - script: |
#      dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC"
