pool:
  vmImage: 'windows-2022'

trigger:
  - main
  - release/*

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'windows-2022'

    steps:
    - checkout: self
      clean: 'true'
      fetchDepth: 0

    - task: UseDotNet@2
      displayName: 'Use .NET SDK'
      inputs:
        version: 9.0.100-rc.1.24452.12
        includePreviewVersions: true
    
    - pwsh: |
        dotnet new install uno.templates
        dotnet new unoapp --platforms windows -tfm net9.0 -o test01

        $msbuild = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe

        cd test01
        & $msbuild /r /p:TargetFramework=net9.0-windows10.0.19041

    - task: PublishPipelineArtifact@1
      condition: always()
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: dotnet-sdk-binaries