pool:
  vmImage: 'windows-2022'

trigger:
  - main
  - release/*

# steps:
#  - bash: |
#     whereis mono
#     sudo apt install gtk-sharp2
#     git clone --recurse-submodules https://github.com/mono/SkiaSharp.git
#     cd SkiaSharp
#     dotnet tool restore
#     dotnet cake --target=externals-download
#     msbuild /r /v:d /p:Configuration=Release /p:BuildingInsideUnoSourceGenerator=true source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SkiaSharp.Views.Uno.Wasm.csproj
#     # dotnet cake --target=libs --skipExternals="all"

# resources:
#   containers:
#   - container: nv-bionic-wasm
#     image: unoplatform/wasm-build:3.0

stages:
- stage: Build
  jobs:
  - job: Build

    # container:
    #   image: unoplatform/wasm-build:3.0
    #   options: "--name ci-container --shm-size=2gb"

    steps:
    - checkout: self
      clean: 'true'
      fetchDepth: 0

    - checkout: self
      clean: true
      
    - task: UseDotNet@2
      displayName: 'Use .NET SDK'
      retryCountOnTaskFailure: 3
      inputs:
        version: 8.0.200
        #includePreviewVersions: true

    - pwsh: |
        dotnet nuget add source -n uno_dev "https://pkgs.dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_packaging/unoplatformdev/nuget/v3/index.json"
        dotnet nuget add source -n net8 "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json"
        dotnet new install uno.templates::5.2.0-dev.80

        dotnet tool install --global Uno.Check --version 1.20.0
        & uno-check -v --ci --non-interactive --fix --skip xcode --skip gtk3 --skip vswin --skip androidemulator --skip androidsdk --skip vsmac

    - pwsh: |
        dotnet workload update --print-rollback
 