pool:
  vmImage: 'windows-2022'

trigger:
  - main
  - release/*

stages:
- stage: Build
  jobs:
  - job: Build

    steps:
    - checkout: self
      clean: 'true'
      fetchDepth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '9.0.100-rc.1.24452.12'
        include-prerelease: true
    
    - pwsh: |
        cd testnet9
        dotnet build

    - task: PublishPipelineArtifact@1
      condition: always()
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: dotnet-sdk-binaries