pool:
  vmImage: 'ubuntu-latest'

trigger:
  - master

steps:
 - bash: |
    whereis mono
    sudo apt install gtk-sharp2
    git clone --recurse-submodules https://github.com/mono/SkiaSharp.git
    cd SkiaSharp
    dotnet tool restore
    dotnet cake --target=externals-download
    dotnet cake --target=libs --skipExternals="all"
