pool:
  vmImage: 'windows-2022'

trigger:
  - main
  - release/*

stages:
- stage: Setup
  jobs:
  - job: Pipeline_Validations

    pool:
      vmImage: 'ubuntu-latest'

      steps:
      - bash: |
            set -euo pipefail
            set -x
            # We use google-chrome instead of chromium-browser because ubuntu uses snap
            # for the chromium package, and snapd isn't available in CI
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt-get update
            sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        displayName: Install chrome

      - bash: |
            set -euo pipefail
            set -x

            # https://github.com/sfinktah/bash/blob/master/rawurlencode.inc.sh
            rawurlencode() {
                local string="${1}"
                local strlen=${#string}
                local encoded=""
                local pos c o

                for (( pos=0 ; pos<strlen ; pos++ )); do
                    c=${string:$pos:1}
                    case "$c" in
                      [-_.~a-zA-Z0-9] ) o="${c}" ;;
                      * )               printf -v o '%%%02x' "'$c"
                    esac
                    encoded+="${o}"
                done
                ENCODED_RESULT="${encoded}"
            }
        
            # For Skia-WASM, SamplesApp is set up so that when saving files, it
            # sends a POST request at HOSTNAME:PORT+1 where HOSTNAME and PORT are
            # the hostname and port of the server that serves the SamplesApp
            python -m http.server 8000 -d "$(build.sourcesdirectory)" &
            python $(build.sourcesdirectory) 8001 &
            sleep 2

            rawurlencode "$(build.sourcesdirectory)/build/skia-browserwasm-runtime-tests-results.xml"
        
            # we use xvfb instead of headless chrome because using --enable-logging with --headless doesn't
            # print the logs as expected
            # for some reason, you have to run the next line twice or else it doesn't work
            xvfb-run --server-num 99 google-chrome --enable-logging=stderr --no-sandbox "http://localhost:8000/?--runtime-tests=${ENCODED_RESULT}" &
            sleep 2
            pkill chrome
            pkill xvfb-run
            xvfb-run --server-num 98 google-chrome --enable-logging=stderr --no-sandbox "http://localhost:8000/?--runtime-tests=${ENCODED_RESULT}" &

            while ! test -f "$(build.sourcesdirectory)/build/skia-browserwasm-runtime-tests-results.xml"; do
                sleep 10
            done

        displayName: Run Skia Browser $(XAML_FLAVOR_BUILD) Runtime Tests
