pool:
  vmImage: 'macOS-10.15'

trigger:
  - master

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 6.0.200
      performMultiLevelLookup: true
  # - pwsh: Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.sh" -OutFile dotnet-install.sh
  # - bash: sh dotnet-install.sh --version "6.0.200" --install-dir "/Users/runner/hostedtoolcache/dotnet" --azure-feed "https://dotnetbuilds.blob.core.windows.net/public" --verbose
  - pwsh: dotnet --info
