name: build
on: 
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: macOS-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6.0.200-preview.22055.15
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.200-preview.22055.15'
      - name: versions
        run: |
          dotnet --version
          dotnet --list-sdks
      - name: new
        run: |
          dotnet new maui -o myApp
      - name: build
        run: |
          dotnet build myApp
