name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
      - name: Install Visual Studio Preview
        run: |
          dotnet tool update -g dotnet-vs
          vs install Enterprise --quiet -pre +mobile
      - name: versions
        run: dotnet --info
      - name: workloads
        run: dotnet workload install maui
      - name: new
        run: dotnet new maui -o myApp

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true

      - name: build
        run: msbuild myApp
