name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6.0.200-preview.22055.15
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.200-preview.22055.15'
      - name: versions
        run: dotnet --info
      - name: workloads
        run: dotnet workload install maui
      - name: new
        run: dotnet new maui -o myApp
      - name: build
        run: dotnet build myApp
